image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-browser
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
      bundle install &&
      rails db:setup RAILS_ENV=development &&
      rails db:reset db:migrate RAILS_ENV=test

github:
  prebuilds:
    branches: false
    pullRequests: true

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby