require: 
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FormatStringToken:
  Enabled: false