version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  web:
    image: fugu/fugu:latest
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@$db:5432/${DATABASE_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT}
      - SENTRY_DSN=${SENTRY_DSN}
