version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile.docker.dev"
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_NAME_TEST=${DATABASE_NAME}
      - SENTRY_DSN=${SENTRY_DSN}
      - ALLOW_NEW_ACCOUNTS=${ALLOW_NEW_ACCOUNTS}
