name: Security

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true

      - name: Check code vulnerabilities
        run: |
          bundle exec brakeman
      - name: Check gem vulnerabilities
        run: |
          bundle exec bundle-audit --update